In [241]:
import pyodbc
import pandas as pd
from pandas import DataFrame, Series
import json
import plotly
plotly.tools.set_credentials_file(username = 'izzy888', api_key = 'Kx3NbXo7kqbVmU9Yg98t')
import cufflinks
import datetime

In [ ]:
# izzy's ip/sql connectors
#SQL Server 12.0.5203.0 - KG-TRAINING17\STUDENT
#IP address =  10.50.0.86

In [242]:
#conn = pyodbc.connect('DRIVER={SQL Server};SERVER=localhost;DATABASE=GeneralElectionTwitter;UID=student;PWD=password')
conn = pyodbc.connect('DSN=GeneralElectionTwitter')

In [243]:
cursor = conn.cursor()

In [244]:
# create a query string in the cursor method

In [249]:
querystring = 'select * from [GeneralElectionTwitter].[clean].[PollData]'

In [250]:
cursor.execute(querystring)

In [251]:
polls = cursor.fetchall()

 pp = [list(p) for p in polls] # make it so can create columns

In [252]:
pp = [list(p) for p in polls]

In [253]:
pp

[[datetime.date(2017, 4, 2), 43.0, 25.0, 11.0, 11.0, 4.0, 5.0],
 [datetime.date(2017, 4, 6), 42.0, 25.0, 11.0, 11.0, 3.0, 0.0],
 [datetime.date(2017, 4, 13), 42.0, 25.0, 10.0, 11.0, 4.0, 3.0],
 [datetime.date(2017, 4, 17), 44.0, 26.0, 10.0, 11.0, 4.0, 4.0],
 [datetime.date(2017, 4, 18), 46.0, 25.0, 11.0, 8.0, 4.0, 4.0],
 [datetime.date(2017, 4, 19), 48.0, 24.0, 12.0, 7.0, 2.0, 0.0],
 [datetime.date(2017, 4, 20), 47.0, 25.0, 11.0, 8.0, 3.0, 4.0],
 [datetime.date(2017, 4, 21), 48.0, 25.0, 12.0, 5.0, 2.0, 0.0],
 [datetime.date(2017, 4, 22), 40.0, 29.0, 11.0, 11.0, 2.0, 4.0],
 [datetime.date(2017, 4, 24), 48.0, 27.0, 10.0, 7.0, 3.0, 4.0],
 [datetime.date(2017, 4, 28), 45.0, 30.0, 9.0, 7.0, 2.0, 2.0],
 [datetime.date(2017, 5, 2), 47.0, 27.0, 9.0, 6.0, 3.0, 3.0],
 [datetime.date(2017, 5, 3), 47.0, 29.0, 9.0, 6.0, 2.0, 2.0],
 [datetime.date(2017, 5, 4), 46.0, 31.0, 9.0, 7.0, 0.0, 3.0],
 [datetime.date(2017, 5, 5), 46.0, 28.0, 10.0, 7.0, 3.0, 2.0],
 [datetime.date(2017, 5, 6), 47.0, 30.0, 7.0, 5.0, 3.0, 5.0],
 [datetime.date(2017, 5, 7), 49.0, 27.0, 9.0, 6.0, 3.0, 4.0],
 [datetime.date(2017, 5, 8), 44.0, 28.0, 11.0, 8.0, 5.0, 4.0],
 [datetime.date(2017, 5, 9), 48.0, 31.0, 8.0, 5.0, 2.0, 4.0],
 [datetime.date(2017, 5, 10), 46.0, 30.0, 11.0, 5.0, 2.0, 0.0],
 [datetime.date(2017, 5, 11), 46.0, 32.0, 8.0, 6.0, 0.0, 5.0],
 [datetime.date(2017, 5, 12), 48.0, 31.0, 9.0, 4.0, 2.0, 3.0],
 [datetime.date(2017, 5, 13), 48.0, 30.0, 8.0, 4.0, 2.0, 4.0],
 [datetime.date(2017, 5, 14), 48.0, 28.0, 8.0, 5.0, 3.0, 5.0],
 [datetime.date(2017, 5, 15), 47.0, 31.0, 7.0, 5.0, 3.0, 4.0],
 [datetime.date(2017, 5, 17), 46.0, 33.0, 7.0, 4.0, 2.0, 3.0],
 [datetime.date(2017, 5, 18), 46.0, 34.0, 7.0, 7.0, 0.0, 4.0],
 [datetime.date(2017, 5, 19), 44.0, 35.0, 9.0, 3.0, 2.0, 0.0],
 [datetime.date(2017, 5, 20), 44.0, 34.0, 8.0, 3.0, 1.0, 3.0]]

In [254]:
pl = DataFrame(data=pp, columns= [ 'Date', 'Con','Lab','LD', 'UKIP', 'GRN', 'SNP'])# add column names back in

In [255]:
pl

          Date   Con   Lab    LD  UKIP  GRN  SNP
0   2017-04-02  43.0  25.0  11.0  11.0  4.0  5.0
1   2017-04-06  42.0  25.0  11.0  11.0  3.0  0.0
2   2017-04-13  42.0  25.0  10.0  11.0  4.0  3.0
3   2017-04-17  44.0  26.0  10.0  11.0  4.0  4.0
4   2017-04-18  46.0  25.0  11.0   8.0  4.0  4.0
5   2017-04-19  48.0  24.0  12.0   7.0  2.0  0.0
6   2017-04-20  47.0  25.0  11.0   8.0  3.0  4.0
7   2017-04-21  48.0  25.0  12.0   5.0  2.0  0.0
8   2017-04-22  40.0  29.0  11.0  11.0  2.0  4.0
9   2017-04-24  48.0  27.0  10.0   7.0  3.0  4.0
10  2017-04-28  45.0  30.0   9.0   7.0  2.0  2.0
11  2017-05-02  47.0  27.0   9.0   6.0  3.0  3.0
12  2017-05-03  47.0  29.0   9.0   6.0  2.0  2.0
13  2017-05-04  46.0  31.0   9.0   7.0  0.0  3.0
14  2017-05-05  46.0  28.0  10.0   7.0  3.0  2.0
15  2017-05-06  47.0  30.0   7.0   5.0  3.0  5.0
16  2017-05-07  49.0  27.0   9.0   6.0  3.0  4.0
17  2017-05-08  44.0  28.0  11.0   8.0  5.0  4.0
18  2017-05-09  48.0  31.0   8.0   5.0  2.0  4.0
19  2017-05-10  46.0  30.0  11.0   5.0  2.0  0.0
20  2017-05-11  46.0  32.0   8.0   6.0  0.0  5.0
21  2017-05-12  48.0  31.0   9.0   4.0  2.0  3.0
22  2017-05-13  48.0  30.0   8.0   4.0  2.0  4.0
23  2017-05-14  48.0  28.0   8.0   5.0  3.0  5.0
24  2017-05-15  47.0  31.0   7.0   5.0  3.0  4.0
25  2017-05-17  46.0  33.0   7.0   4.0  2.0  3.0
26  2017-05-18  46.0  34.0   7.0   7.0  0.0  4.0
27  2017-05-19  44.0  35.0   9.0   3.0  2.0  0.0
28  2017-05-20  44.0  34.0   8.0   3.0  1.0  3.0

In [256]:
pl1 = DataFrame(data=pp, columns= [ 'Date', 'Con','Lab','LD', 'UKIP', 'GRN', 'SNP'])# back-up DF for time-series

In [257]:
def fill_in_missing_dates( pl1, date_col_name = 'Date', date_order = 'asc', method = 'ffill', day_back = 40):
    pl1.set_index(date_col_name,drop=True,inplace=True)
    pl1.index = pd.DatetimeIndex(pl1.index)
    d = datetime.now().date()
    d2 = d - timedelta(days = days_back) # a way to fill in values for all polls coming in since snap election was called
    idx = pd.date_range(d2, d, freq = "D")
    pl1 = pl1.reindex(idx, method = 'ffill')
    pl1[date_col_name] = pd.DatetimeIndex(pl1.index)

    return pl1

In [258]:
pl1

          Date   Con   Lab    LD  UKIP  GRN  SNP
0   2017-04-02  43.0  25.0  11.0  11.0  4.0  5.0
1   2017-04-06  42.0  25.0  11.0  11.0  3.0  0.0
2   2017-04-13  42.0  25.0  10.0  11.0  4.0  3.0
3   2017-04-17  44.0  26.0  10.0  11.0  4.0  4.0
4   2017-04-18  46.0  25.0  11.0   8.0  4.0  4.0
5   2017-04-19  48.0  24.0  12.0   7.0  2.0  0.0
6   2017-04-20  47.0  25.0  11.0   8.0  3.0  4.0
7   2017-04-21  48.0  25.0  12.0   5.0  2.0  0.0
8   2017-04-22  40.0  29.0  11.0  11.0  2.0  4.0
9   2017-04-24  48.0  27.0  10.0   7.0  3.0  4.0
10  2017-04-28  45.0  30.0   9.0   7.0  2.0  2.0
11  2017-05-02  47.0  27.0   9.0   6.0  3.0  3.0
12  2017-05-03  47.0  29.0   9.0   6.0  2.0  2.0
13  2017-05-04  46.0  31.0   9.0   7.0  0.0  3.0
14  2017-05-05  46.0  28.0  10.0   7.0  3.0  2.0
15  2017-05-06  47.0  30.0   7.0   5.0  3.0  5.0
16  2017-05-07  49.0  27.0   9.0   6.0  3.0  4.0
17  2017-05-08  44.0  28.0  11.0   8.0  5.0  4.0
18  2017-05-09  48.0  31.0   8.0   5.0  2.0  4.0
19  2017-05-10  46.0  30.0  11.0   5.0  2.0  0.0
20  2017-05-11  46.0  32.0   8.0   6.0  0.0  5.0
21  2017-05-12  48.0  31.0   9.0   4.0  2.0  3.0
22  2017-05-13  48.0  30.0   8.0   4.0  2.0  4.0
23  2017-05-14  48.0  28.0   8.0   5.0  3.0  5.0
24  2017-05-15  47.0  31.0   7.0   5.0  3.0  4.0
25  2017-05-17  46.0  33.0   7.0   4.0  2.0  3.0
26  2017-05-18  46.0  34.0   7.0   7.0  0.0  4.0
27  2017-05-19  44.0  35.0   9.0   3.0  2.0  0.0
28  2017-05-20  44.0  34.0   8.0   3.0  1.0  3.0

In [259]:
minDate = pl1.min()['Date']

In [260]:
idx = pd.date_range(minDate, '15-05-2017')

In [261]:
pl1.index = pd.DatetimeIndex(pl1.Date) #made the index a date

In [262]:
pl1.dtypes

Date     object
Con     float64
Lab     float64
LD      float64
UKIP    float64
GRN     float64
SNP     float64
dtype: object

In [263]:
pl1

                  Date   Con   Lab    LD  UKIP  GRN  SNP
Date
2017-04-02  2017-04-02  43.0  25.0  11.0  11.0  4.0  5.0
2017-04-06  2017-04-06  42.0  25.0  11.0  11.0  3.0  0.0
2017-04-13  2017-04-13  42.0  25.0  10.0  11.0  4.0  3.0
2017-04-17  2017-04-17  44.0  26.0  10.0  11.0  4.0  4.0
2017-04-18  2017-04-18  46.0  25.0  11.0   8.0  4.0  4.0
2017-04-19  2017-04-19  48.0  24.0  12.0   7.0  2.0  0.0
2017-04-20  2017-04-20  47.0  25.0  11.0   8.0  3.0  4.0
2017-04-21  2017-04-21  48.0  25.0  12.0   5.0  2.0  0.0
2017-04-22  2017-04-22  40.0  29.0  11.0  11.0  2.0  4.0
2017-04-24  2017-04-24  48.0  27.0  10.0   7.0  3.0  4.0
2017-04-28  2017-04-28  45.0  30.0   9.0   7.0  2.0  2.0
2017-05-02  2017-05-02  47.0  27.0   9.0   6.0  3.0  3.0
2017-05-03  2017-05-03  47.0  29.0   9.0   6.0  2.0  2.0
2017-05-04  2017-05-04  46.0  31.0   9.0   7.0  0.0  3.0
2017-05-05  2017-05-05  46.0  28.0  10.0   7.0  3.0  2.0
2017-05-06  2017-05-06  47.0  30.0   7.0   5.0  3.0  5.0
2017-05-07  2017-05-07  49.0  27.0   9.0   6.0  3.0  4.0
2017-05-08  2017-05-08  44.0  28.0  11.0   8.0  5.0  4.0
2017-05-09  2017-05-09  48.0  31.0   8.0   5.0  2.0  4.0
2017-05-10  2017-05-10  46.0  30.0  11.0   5.0  2.0  0.0
2017-05-11  2017-05-11  46.0  32.0   8.0   6.0  0.0  5.0
2017-05-12  2017-05-12  48.0  31.0   9.0   4.0  2.0  3.0
2017-05-13  2017-05-13  48.0  30.0   8.0   4.0  2.0  4.0
2017-05-14  2017-05-14  48.0  28.0   8.0   5.0  3.0  5.0
2017-05-15  2017-05-15  47.0  31.0   7.0   5.0  3.0  4.0
2017-05-17  2017-05-17  46.0  33.0   7.0   4.0  2.0  3.0
2017-05-18  2017-05-18  46.0  34.0   7.0   7.0  0.0  4.0
2017-05-19  2017-05-19  44.0  35.0   9.0   3.0  2.0  0.0
2017-05-20  2017-05-20  44.0  34.0   8.0   3.0  1.0  3.0

In [264]:
pl1['Date']= pd.to_datetime(pl1['Date'])

In [265]:
pl1 = pl1.reindex(idx, method = 'ffill')

In [266]:
pl1

                 Date   Con   Lab    LD  UKIP  GRN  SNP
2017-04-02 2017-04-02  43.0  25.0  11.0  11.0  4.0  5.0
2017-04-03 2017-04-02  43.0  25.0  11.0  11.0  4.0  5.0
2017-04-04 2017-04-02  43.0  25.0  11.0  11.0  4.0  5.0
2017-04-05 2017-04-02  43.0  25.0  11.0  11.0  4.0  5.0
2017-04-06 2017-04-06  42.0  25.0  11.0  11.0  3.0  0.0
2017-04-07 2017-04-06  42.0  25.0  11.0  11.0  3.0  0.0
2017-04-08 2017-04-06  42.0  25.0  11.0  11.0  3.0  0.0
2017-04-09 2017-04-06  42.0  25.0  11.0  11.0  3.0  0.0
2017-04-10 2017-04-06  42.0  25.0  11.0  11.0  3.0  0.0
2017-04-11 2017-04-06  42.0  25.0  11.0  11.0  3.0  0.0
2017-04-12 2017-04-06  42.0  25.0  11.0  11.0  3.0  0.0
2017-04-13 2017-04-13  42.0  25.0  10.0  11.0  4.0  3.0
2017-04-14 2017-04-13  42.0  25.0  10.0  11.0  4.0  3.0
2017-04-15 2017-04-13  42.0  25.0  10.0  11.0  4.0  3.0
2017-04-16 2017-04-13  42.0  25.0  10.0  11.0  4.0  3.0
2017-04-17 2017-04-17  44.0  26.0  10.0  11.0  4.0  4.0
2017-04-18 2017-04-18  46.0  25.0  11.0   8.0  4.0  4.0
2017-04-19 2017-04-19  48.0  24.0  12.0   7.0  2.0  0.0
2017-04-20 2017-04-20  47.0  25.0  11.0   8.0  3.0  4.0
2017-04-21 2017-04-21  48.0  25.0  12.0   5.0  2.0  0.0
2017-04-22 2017-04-22  40.0  29.0  11.0  11.0  2.0  4.0
2017-04-23 2017-04-22  40.0  29.0  11.0  11.0  2.0  4.0
2017-04-24 2017-04-24  48.0  27.0  10.0   7.0  3.0  4.0
2017-04-25 2017-04-24  48.0  27.0  10.0   7.0  3.0  4.0
2017-04-26 2017-04-24  48.0  27.0  10.0   7.0  3.0  4.0
2017-04-27 2017-04-24  48.0  27.0  10.0   7.0  3.0  4.0
2017-04-28 2017-04-28  45.0  30.0   9.0   7.0  2.0  2.0
2017-04-29 2017-04-28  45.0  30.0   9.0   7.0  2.0  2.0
2017-04-30 2017-04-28  45.0  30.0   9.0   7.0  2.0  2.0
2017-05-01 2017-04-28  45.0  30.0   9.0   7.0  2.0  2.0
2017-05-02 2017-05-02  47.0  27.0   9.0   6.0  3.0  3.0
2017-05-03 2017-05-03  47.0  29.0   9.0   6.0  2.0  2.0
2017-05-04 2017-05-04  46.0  31.0   9.0   7.0  0.0  3.0
2017-05-05 2017-05-05  46.0  28.0  10.0   7.0  3.0  2.0
2017-05-06 2017-05-06  47.0  30.0   7.0   5.0  3.0  5.0
2017-05-07 2017-05-07  49.0  27.0   9.0   6.0  3.0  4.0
2017-05-08 2017-05-08  44.0  28.0  11.0   8.0  5.0  4.0
2017-05-09 2017-05-09  48.0  31.0   8.0   5.0  2.0  4.0
2017-05-10 2017-05-10  46.0  30.0  11.0   5.0  2.0  0.0
2017-05-11 2017-05-11  46.0  32.0   8.0   6.0  0.0  5.0
2017-05-12 2017-05-12  48.0  31.0   9.0   4.0  2.0  3.0
2017-05-13 2017-05-13  48.0  30.0   8.0   4.0  2.0  4.0
2017-05-14 2017-05-14  48.0  28.0   8.0   5.0  3.0  5.0
2017-05-15 2017-05-15  47.0  31.0   7.0   5.0  3.0  4.0

In [267]:
# now going to get rid of the date col and rename the index to be the date col
del pl1['Date']

In [268]:
pl1

             Con   Lab    LD  UKIP  GRN  SNP
2017-04-02  43.0  25.0  11.0  11.0  4.0  5.0
2017-04-03  43.0  25.0  11.0  11.0  4.0  5.0
2017-04-04  43.0  25.0  11.0  11.0  4.0  5.0
2017-04-05  43.0  25.0  11.0  11.0  4.0  5.0
2017-04-06  42.0  25.0  11.0  11.0  3.0  0.0
2017-04-07  42.0  25.0  11.0  11.0  3.0  0.0
2017-04-08  42.0  25.0  11.0  11.0  3.0  0.0
2017-04-09  42.0  25.0  11.0  11.0  3.0  0.0
2017-04-10  42.0  25.0  11.0  11.0  3.0  0.0
2017-04-11  42.0  25.0  11.0  11.0  3.0  0.0
2017-04-12  42.0  25.0  11.0  11.0  3.0  0.0
2017-04-13  42.0  25.0  10.0  11.0  4.0  3.0
2017-04-14  42.0  25.0  10.0  11.0  4.0  3.0
2017-04-15  42.0  25.0  10.0  11.0  4.0  3.0
2017-04-16  42.0  25.0  10.0  11.0  4.0  3.0
2017-04-17  44.0  26.0  10.0  11.0  4.0  4.0
2017-04-18  46.0  25.0  11.0   8.0  4.0  4.0
2017-04-19  48.0  24.0  12.0   7.0  2.0  0.0
2017-04-20  47.0  25.0  11.0   8.0  3.0  4.0
2017-04-21  48.0  25.0  12.0   5.0  2.0  0.0
2017-04-22  40.0  29.0  11.0  11.0  2.0  4.0
2017-04-23  40.0  29.0  11.0  11.0  2.0  4.0
2017-04-24  48.0  27.0  10.0   7.0  3.0  4.0
2017-04-25  48.0  27.0  10.0   7.0  3.0  4.0
2017-04-26  48.0  27.0  10.0   7.0  3.0  4.0
2017-04-27  48.0  27.0  10.0   7.0  3.0  4.0
2017-04-28  45.0  30.0   9.0   7.0  2.0  2.0
2017-04-29  45.0  30.0   9.0   7.0  2.0  2.0
2017-04-30  45.0  30.0   9.0   7.0  2.0  2.0
2017-05-01  45.0  30.0   9.0   7.0  2.0  2.0
2017-05-02  47.0  27.0   9.0   6.0  3.0  3.0
2017-05-03  47.0  29.0   9.0   6.0  2.0  2.0
2017-05-04  46.0  31.0   9.0   7.0  0.0  3.0
2017-05-05  46.0  28.0  10.0   7.0  3.0  2.0
2017-05-06  47.0  30.0   7.0   5.0  3.0  5.0
2017-05-07  49.0  27.0   9.0   6.0  3.0  4.0
2017-05-08  44.0  28.0  11.0   8.0  5.0  4.0
2017-05-09  48.0  31.0   8.0   5.0  2.0  4.0
2017-05-10  46.0  30.0  11.0   5.0  2.0  0.0
2017-05-11  46.0  32.0   8.0   6.0  0.0  5.0
2017-05-12  48.0  31.0   9.0   4.0  2.0  3.0
2017-05-13  48.0  30.0   8.0   4.0  2.0  4.0
2017-05-14  48.0  28.0   8.0   5.0  3.0  5.0
2017-05-15  47.0  31.0   7.0   5.0  3.0  4.0

In [269]:
pl1.reset_index(inplace = True)

In [270]:
pl1.rename(columns = {'index':'Date'}, inplace = True )

In [271]:
pl1

         Date   Con   Lab    LD  UKIP  GRN  SNP
0  2017-04-02  43.0  25.0  11.0  11.0  4.0  5.0
1  2017-04-03  43.0  25.0  11.0  11.0  4.0  5.0
2  2017-04-04  43.0  25.0  11.0  11.0  4.0  5.0
3  2017-04-05  43.0  25.0  11.0  11.0  4.0  5.0
4  2017-04-06  42.0  25.0  11.0  11.0  3.0  0.0
5  2017-04-07  42.0  25.0  11.0  11.0  3.0  0.0
6  2017-04-08  42.0  25.0  11.0  11.0  3.0  0.0
7  2017-04-09  42.0  25.0  11.0  11.0  3.0  0.0
8  2017-04-10  42.0  25.0  11.0  11.0  3.0  0.0
9  2017-04-11  42.0  25.0  11.0  11.0  3.0  0.0
10 2017-04-12  42.0  25.0  11.0  11.0  3.0  0.0
11 2017-04-13  42.0  25.0  10.0  11.0  4.0  3.0
12 2017-04-14  42.0  25.0  10.0  11.0  4.0  3.0
13 2017-04-15  42.0  25.0  10.0  11.0  4.0  3.0
14 2017-04-16  42.0  25.0  10.0  11.0  4.0  3.0
15 2017-04-17  44.0  26.0  10.0  11.0  4.0  4.0
16 2017-04-18  46.0  25.0  11.0   8.0  4.0  4.0
17 2017-04-19  48.0  24.0  12.0   7.0  2.0  0.0
18 2017-04-20  47.0  25.0  11.0   8.0  3.0  4.0
19 2017-04-21  48.0  25.0  12.0   5.0  2.0  0.0
20 2017-04-22  40.0  29.0  11.0  11.0  2.0  4.0
21 2017-04-23  40.0  29.0  11.0  11.0  2.0  4.0
22 2017-04-24  48.0  27.0  10.0   7.0  3.0  4.0
23 2017-04-25  48.0  27.0  10.0   7.0  3.0  4.0
24 2017-04-26  48.0  27.0  10.0   7.0  3.0  4.0
25 2017-04-27  48.0  27.0  10.0   7.0  3.0  4.0
26 2017-04-28  45.0  30.0   9.0   7.0  2.0  2.0
27 2017-04-29  45.0  30.0   9.0   7.0  2.0  2.0
28 2017-04-30  45.0  30.0   9.0   7.0  2.0  2.0
29 2017-05-01  45.0  30.0   9.0   7.0  2.0  2.0
30 2017-05-02  47.0  27.0   9.0   6.0  3.0  3.0
31 2017-05-03  47.0  29.0   9.0   6.0  2.0  2.0
32 2017-05-04  46.0  31.0   9.0   7.0  0.0  3.0
33 2017-05-05  46.0  28.0  10.0   7.0  3.0  2.0
34 2017-05-06  47.0  30.0   7.0   5.0  3.0  5.0
35 2017-05-07  49.0  27.0   9.0   6.0  3.0  4.0
36 2017-05-08  44.0  28.0  11.0   8.0  5.0  4.0
37 2017-05-09  48.0  31.0   8.0   5.0  2.0  4.0
38 2017-05-10  46.0  30.0  11.0   5.0  2.0  0.0
39 2017-05-11  46.0  32.0   8.0   6.0  0.0  5.0
40 2017-05-12  48.0  31.0   9.0   4.0  2.0  3.0
41 2017-05-13  48.0  30.0   8.0   4.0  2.0  4.0
42 2017-05-14  48.0  28.0   8.0   5.0  3.0  5.0
43 2017-05-15  47.0  31.0   7.0   5.0  3.0  4.0

In [297]:
#this converts the polls dataframe to a csv for use for plotting if cant connect to my SQL

pl1.to_csv('C:\Users\Student\Documents\poll.csv')

In [274]:
connection.commit()

In [275]:
polls

[(datetime.date(2017, 4, 2), 43.0, 25.0, 11.0, 11.0, 4.0, 5.0),
 (datetime.date(2017, 4, 6), 42.0, 25.0, 11.0, 11.0, 3.0, 0.0),
 (datetime.date(2017, 4, 13), 42.0, 25.0, 10.0, 11.0, 4.0, 3.0),
 (datetime.date(2017, 4, 17), 44.0, 26.0, 10.0, 11.0, 4.0, 4.0),
 (datetime.date(2017, 4, 18), 46.0, 25.0, 11.0, 8.0, 4.0, 4.0),
 (datetime.date(2017, 4, 19), 48.0, 24.0, 12.0, 7.0, 2.0, 0.0),
 (datetime.date(2017, 4, 20), 47.0, 25.0, 11.0, 8.0, 3.0, 4.0),
 (datetime.date(2017, 4, 21), 48.0, 25.0, 12.0, 5.0, 2.0, 0.0),
 (datetime.date(2017, 4, 22), 40.0, 29.0, 11.0, 11.0, 2.0, 4.0),
 (datetime.date(2017, 4, 24), 48.0, 27.0, 10.0, 7.0, 3.0, 4.0),
 (datetime.date(2017, 4, 28), 45.0, 30.0, 9.0, 7.0, 2.0, 2.0),
 (datetime.date(2017, 5, 2), 47.0, 27.0, 9.0, 6.0, 3.0, 3.0),
 (datetime.date(2017, 5, 3), 47.0, 29.0, 9.0, 6.0, 2.0, 2.0),
 (datetime.date(2017, 5, 4), 46.0, 31.0, 9.0, 7.0, 0.0, 3.0),
 (datetime.date(2017, 5, 5), 46.0, 28.0, 10.0, 7.0, 3.0, 2.0),
 (datetime.date(2017, 5, 6), 47.0, 30.0, 7.0, 5.0, 3.0, 5.0),
 (datetime.date(2017, 5, 7), 49.0, 27.0, 9.0, 6.0, 3.0, 4.0),
 (datetime.date(2017, 5, 8), 44.0, 28.0, 11.0, 8.0, 5.0, 4.0),
 (datetime.date(2017, 5, 9), 48.0, 31.0, 8.0, 5.0, 2.0, 4.0),
 (datetime.date(2017, 5, 10), 46.0, 30.0, 11.0, 5.0, 2.0, 0.0),
 (datetime.date(2017, 5, 11), 46.0, 32.0, 8.0, 6.0, 0.0, 5.0),
 (datetime.date(2017, 5, 12), 48.0, 31.0, 9.0, 4.0, 2.0, 3.0),
 (datetime.date(2017, 5, 13), 48.0, 30.0, 8.0, 4.0, 2.0, 4.0),
 (datetime.date(2017, 5, 14), 48.0, 28.0, 8.0, 5.0, 3.0, 5.0),
 (datetime.date(2017, 5, 15), 47.0, 31.0, 7.0, 5.0, 3.0, 4.0),
 (datetime.date(2017, 5, 17), 46.0, 33.0, 7.0, 4.0, 2.0, 3.0),
 (datetime.date(2017, 5, 18), 46.0, 34.0, 7.0, 7.0, 0.0, 4.0),
 (datetime.date(2017, 5, 19), 44.0, 35.0, 9.0, 3.0, 2.0, 0.0),
 (datetime.date(2017, 5, 20), 44.0, 34.0, 8.0, 3.0, 1.0, 3.0)]

In [276]:
p = list(polls)

In [277]:
p

[(datetime.date(2017, 4, 2), 43.0, 25.0, 11.0, 11.0, 4.0, 5.0),
 (datetime.date(2017, 4, 6), 42.0, 25.0, 11.0, 11.0, 3.0, 0.0),
 (datetime.date(2017, 4, 13), 42.0, 25.0, 10.0, 11.0, 4.0, 3.0),
 (datetime.date(2017, 4, 17), 44.0, 26.0, 10.0, 11.0, 4.0, 4.0),
 (datetime.date(2017, 4, 18), 46.0, 25.0, 11.0, 8.0, 4.0, 4.0),
 (datetime.date(2017, 4, 19), 48.0, 24.0, 12.0, 7.0, 2.0, 0.0),
 (datetime.date(2017, 4, 20), 47.0, 25.0, 11.0, 8.0, 3.0, 4.0),
 (datetime.date(2017, 4, 21), 48.0, 25.0, 12.0, 5.0, 2.0, 0.0),
 (datetime.date(2017, 4, 22), 40.0, 29.0, 11.0, 11.0, 2.0, 4.0),
 (datetime.date(2017, 4, 24), 48.0, 27.0, 10.0, 7.0, 3.0, 4.0),
 (datetime.date(2017, 4, 28), 45.0, 30.0, 9.0, 7.0, 2.0, 2.0),
 (datetime.date(2017, 5, 2), 47.0, 27.0, 9.0, 6.0, 3.0, 3.0),
 (datetime.date(2017, 5, 3), 47.0, 29.0, 9.0, 6.0, 2.0, 2.0),
 (datetime.date(2017, 5, 4), 46.0, 31.0, 9.0, 7.0, 0.0, 3.0),
 (datetime.date(2017, 5, 5), 46.0, 28.0, 10.0, 7.0, 3.0, 2.0),
 (datetime.date(2017, 5, 6), 47.0, 30.0, 7.0, 5.0, 3.0, 5.0),
 (datetime.date(2017, 5, 7), 49.0, 27.0, 9.0, 6.0, 3.0, 4.0),
 (datetime.date(2017, 5, 8), 44.0, 28.0, 11.0, 8.0, 5.0, 4.0),
 (datetime.date(2017, 5, 9), 48.0, 31.0, 8.0, 5.0, 2.0, 4.0),
 (datetime.date(2017, 5, 10), 46.0, 30.0, 11.0, 5.0, 2.0, 0.0),
 (datetime.date(2017, 5, 11), 46.0, 32.0, 8.0, 6.0, 0.0, 5.0),
 (datetime.date(2017, 5, 12), 48.0, 31.0, 9.0, 4.0, 2.0, 3.0),
 (datetime.date(2017, 5, 13), 48.0, 30.0, 8.0, 4.0, 2.0, 4.0),
 (datetime.date(2017, 5, 14), 48.0, 28.0, 8.0, 5.0, 3.0, 5.0),
 (datetime.date(2017, 5, 15), 47.0, 31.0, 7.0, 5.0, 3.0, 4.0),
 (datetime.date(2017, 5, 17), 46.0, 33.0, 7.0, 4.0, 2.0, 3.0),
 (datetime.date(2017, 5, 18), 46.0, 34.0, 7.0, 7.0, 0.0, 4.0),
 (datetime.date(2017, 5, 19), 44.0, 35.0, 9.0, 3.0, 2.0, 0.0),
 (datetime.date(2017, 5, 20), 44.0, 34.0, 8.0, 3.0, 1.0, 3.0)]

In [278]:

pl.iplot(kind='line', xTitle = 'Date', yTitle = 'Average Poll %', x = ['Date'], y = ['Lab','Con','LD','UKIP','GRN','SNP'])

In [279]:
##plot individually and then put together
import plotly.plotly as py
from plotly.graph_objs import *
import cufflinks